services:
  db:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  cruder-app:
    build: .
    container_name: cruder-app
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DSN: "host=db port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"
    depends_on:
      - db
    restart: on-failure

volumes:
  postgres_data: