apiVersion: apps/v1
kind: Deployment
metadata:
  name: cruder-deployment
  labels:
    app: cruder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cruder
  template:
    metadata:
      labels:
        app: cruder
    spec:
      containers:
      - name: cruder-container
        image: kaurmatthi/cruder-app:1.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: config-volume
            mountPath: /root/config
            readOnly: true
        envFrom:
        - configMapRef:
            name: cruder-env
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
      volumes:
        - name: config-volume
          configMap:
            name: cruder-config
---
apiVersion: v1
kind: Service
metadata:
  name: cruder
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: cruder
  type: LoadBalancer
