apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: cruder
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: goose
          image: gomicro/goose:3.25.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
              echo "Running migrations with command: $MIGRATION_COMMAND"
              goose -dir=/migrations postgres "$DATABASE_URL" $MIGRATION_COMMAND      
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cruder-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: migrations
